Updates

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,8 +1,17 @@
 #!/bin/bash
-set +x
+set -x
+#set -e
 
 BASE_DIR=`cd "$(dirname "$0")"; pwd`
-source "$BASE_DIR"/config
+
+CONFIG=$BASE_DIR/config
+source "$CONFIG" 2> /dev/null || {
+  CONFIG=$CONFIG.sample
+  source "$CONFIG" 2> /dev/null || {
+    echo "File \"$CONFIG\" was not found!"
+    exit 1
+  }
+}
 
 DISK=${DISK:-sda}
 
@@ -17,13 +26,13 @@ PUBKEY=$(cat $PUBKEY_FILE)
 
 cd "$BASE_DIR"
 
-ssh-keygen -R $HOST_IP
+ssh-keygen -R $VM_IP
 
 # copy your public key, so can ssh without a password later on
-ssh -tt -p $HOST_SSH_PORT root@$HOST_IP "rm -rf ~/.ssh; mkdir -m 700 ~/.ssh; echo $PUBKEY > ~/.ssh/authorized_keys; chmod 600 ~/.ssh/authorized_keys"
+ssh -tt -p $VM_SSH_PORT root@$VM_IP "rm -rf ~/.ssh; mkdir -m 700 ~/.ssh; echo $PUBKEY > ~/.ssh/authorized_keys; chmod 600 ~/.ssh/authorized_keys"
 
 # copy install scripts from ./root folder
-scp -P $HOST_SSH_PORT config root/* root@$HOST_IP:~/
+scp -P $VM_SSH_PORT config config.sample root/* root@$VM_IP:~/
 
 # run the install script remotely
-ssh -tt -p $HOST_SSH_PORT root@$HOST_IP "chmod +x ./{install,chroot}; ./install $DISK"
+ssh -tt -p $VM_SSH_PORT root@$VM_IP "chmod +x ./{install,chroot}; ./install $DISK"
